---
version: "3.8"
services:

# Frontend
  frontend:
    build:
      context: ./frontend/
      target: development
    volumes:
      - ./frontend/pages:/app/pages 
      - ./frontend/public:/app/public 
      - ./frontend/src:/app/src
    ports: 
      - 3000:3000

# Backend API
  backend:
    env_file: ./backend/.env
    build: 
      context: ./backend/
      target: development
    depends_on:
      - mariadb
    volumes:
      - ./backend/src:/app/src
    ports:
      - 5001:5001

# Database
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      # Todo: user for the application / dotenv files instead here
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: dbtest
      MYSQL_USER: expressuser
      MYSQL_PASSWORD: expresspassword
    volumes:
      - ./database/sql:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/mysql
      - ./database/config:/etc/mysql/conf.d
