---
version: "3.8"
services:

# Backend API
  backend:
    build: 
      context: ./backend/
      target: development
    volumes:
      - "./backend/src:/app/src"
    ports:
      - '5001:5001'

  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: dbtest
      # MYSQL_USER: 
      # MYSQL_PASSWORD: 
    restart: always
    volumes:
      - "./database/sql:/docker-entrypoint-initdb.d"
      - "./database/data:/var/lib/mysql"
      - "./database/config:/etc/mysql/conf.d"
