export const API_URL = 'http://localhost:5001'
export const CURRENCY = 'SEK'

export const REGISTER_PRODUCER_PATH = '/bli-producent'
export const REGISTER_CUSTOMER_PATH = '/registrera'
export const PRODUCTS_PATH = '/produkter'
export const PRODUCT_CATEGORIES_PATH = '/produkt-kategori'
export const LOGIN_PATH = '/logga-in'
export const PRODUCERS_PATH = '/producenter'
export const CART_PATH = '/varukorg'
export const PRODUCER_DASHBOARD_PATH = '/merchants'
export const LOGO_PATH = '/logga-reko-cirkel.svg'
export const MY_ACCOUNT_PATH = '/mitt-konto'
export const PRODUCT_PLACEHOLDER_IMG_PATH = '/apples.jpg'

export const INKOMMEN = 'Inkommen'
export const MAKULERAD = 'Makulerad'
export const LEVERERAD = 'Levererad'
export const LERVERANSKLAR = 'leveransklar'
